### ISSUE TITLE
Please add install instructions

### ISSUE THREAD

**Issue by amazebb** [zygmuntszpak/ImageBinarization.jl#50]
Please add install instructions for brand new user stumbling across Julia on how to add the package. This will increase usability.

**Comment by johnnychen94** [comment]
This package takes the standard package-installation routine in Julia, i.e., `]add ImageBinarization` is sufficient.

For your information, you'll find descriptions on https://docs.julialang.org/en/v1/stdlib/Pkg/index.html

**Comment by johnnychen94** [comment]
I'm closing this issue because this is not an `ImageBinarization`-specific problem.
