### ISSUE TITLE
Many algorithms do not have docstrings

### ISSUE THREAD

**Issue by JaapHaitsma** [zygmuntszpak/ImageBinarization.jl#85]
Balanced, Entropy, Intermodes,MinimumError,  Minimum Intermodes, Moments,  Unimodal Rosin and Yen don't have docstrings

**Comment by zygmuntszpak** [comment]
Many thanks for reporting this. Something seems to have gone wrong with the docstrings build process. I will have a stab at fixing this ASAP.
